# Copyright (C) 2019-2023 Julian Valentin, LTeX Development Community
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

comments:
  AbsentOrWrongFileLicense:
    active: true
    licenseTemplateFile: ".detekt.license-header.kt"
complexity:
  LongMethod:
    threshold: 75
empty-blocks:
  EmptyFunctionBlock:
    active: false
naming:
  ConstructorParameterNaming:
    privateParameterPattern: "_?[a-z][A-Za-z0-9]*"
style:
  ReturnCount:
    max: 6
