os: "linux"
dist: "bionic"
language: "java"
jdk: "openjdk8"
cache: false
stages:
  - "test"
  - "coverage"
  - "deploy"
jobs:
  include:
    - stage: "test"
      os: "linux"
      script:
        - "mvn -e verify"
    - stage: "test"
      os: "osx"
      jdk: "openjdk11"
      addons:
        homebrew:
          update: true
          taps:
            - "adoptopenjdk/openjdk"
          casks:
            - "adoptopenjdk8"
      before_install:
        - "export JAVA_HOME=\"/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home\""
        - "export PATH=\"$JAVA_HOME/bin:$PATH\""
        - "echo $JAVA_HOME"
        - "echo $PATH"
      script:
        - "mvn -e verify"
    - stage: "test"
      os: "windows"
      language: "shell"
      install:
        - "choco install openjdk8"
        - "choco install maven"
      script:
        - "cmd.exe //C \"RefreshEnv.cmd & mvn -e verify\""
    - stage: "coverage"
      script:
        - "mvn verify -e org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report"
    - stage: "deploy"
      if: "tag IS present"
      install:
        - "sudo apt-get -y install python3-pip"
        - "pip3 install semver"
      script:
        - "mvn package -e"
        - "ltexls-core/target/appassembler/bin/ltex-ls --version > ltexLsVersion.json"
        - "export LTEX_LS_VERSION=\"$(python3 -c \"import json; print(json.load(open('ltexLsVersion.json'))['ltex-ls'], end='')\")\""
        - "rm ltexLsVersion.json"
        - "if [[ -z \"$LTEX_LS_VERSION\" ]]; then echo 'Error: LTEX_LS_VERSION not set!'; (exit 1); fi"
        - "export IS_PRERELEASE=\"$(python3 -c \"import semver; print('1' if semver.VersionInfo.parse('$LTEX_LS_VERSION').prerelease is not None else '0', end='')\")\""
        - "if [[ -z \"$IS_PRERELEASE\" ]]; then echo 'Error: IS_PRERELEASE not set!'; (exit 1); fi"
        - "if [[ \"$IS_PRERELEASE\" -eq \"0\" ]]; then echo 'Detected stable release.'; else echo 'Detected prerelease.'; fi"
      deploy:
        - &deployBlock
          provider: "releases"
          token:
            secure: "GM8rxr6a3tRUKwe8QG85wctWk3DIHBEfOlMZaXxahF3U7MNM8e01kpkkyUREGdF5/ARD4cknZRYBpkNiLgtEZzR8928OgBe5KRtEEubEjUvVrg0IoII+uCxa+OK3OhYvm31FQFnfSJjHSdxcXlHojUsYXttOI78VxiwdZk907yTHwaiR8jSUcU8lAy73i6wGzSLAeNOkyc6oDbSMMyQdJrS499mCOD2u6sO27Nptun52mbpmwpmHc6X2eKJ0JG2PCCkuCQnoxmfBA/qVCv5yEeQ3X3zfMkrg/Ad7mxmWzSVdJccCKl21v1FaZ6yURAQwvI5yuflf1+LCpRiAU92w/pUhbMAJCc7snOM5iBekdkvTVyYcfUlgI6C5NjST102GTZxvhcPq8cxjxlNi5aFIEhnRJBXNATQ5oHHO6kacm62OGJxkYCKAA4MILGSFLK8YtYrDKneLV98raHHSIa1YH/LKX6I0MbTHQlu1KFAA8YL0mnl8zts9DhUdjLH1YQNakPJSj0wg4vbeHMWHsPxRuufAXTE1eMx/rkETiZmz9fClSB5GJi3cvipbGGT3Kn357fDZ30+aRQJY1p3xcDAXD2xQa8CPFmhBcBTtA+lWj8/VYrtrEjusd4KFzefFsoorpnKAZ3luPK7E/LzANZT4jvEpS9XHPKHFRG+hY+4RGEM="
          file: "ltexls-core/target/ltex-ls-*.tar.gz"
          file_glob: true
          # needs to be removed for Travis's dpl v2
          # see https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release#cleaning-up-the-git-working-directory
          skip_cleanup: true
          on:
            repo: "valentjn/ltex-ls"
            tags: true
            condition: "\"$IS_PRERELEASE\" -eq \"0\""
        - <<: *deployBlock
          prerelease: true
          on:
            repo: "valentjn/ltex-ls"
            tags: true
            condition: "\"$IS_PRERELEASE\" -eq \"1\""
